/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.semantic_log_classifier_api.db.tables


import com.kbalazsworks.semantic_log_classifier_api.db.Public
import com.kbalazsworks.semantic_log_classifier_api.db.indexes.IDX_VECTOR_STORE_384_CONTEXT_INFO_GIN
import com.kbalazsworks.semantic_log_classifier_api.db.keys.VECTOR_STORE_384__VECTOR_STORE_384_VECTOR_MODEL_ID_FKEY
import com.kbalazsworks.semantic_log_classifier_api.db.tables.VectorModels.VectorModelsPath
import com.kbalazsworks.semantic_log_classifier_api.db.tables.records.VectorStore_384Record
import com.kbalazsworks.semantic_log_classifier_api.domain.repositories.vector_extension.PgVectorBinding
import com.pgvector.PGvector

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VectorStore_384(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VectorStore_384Record>?,
    parentPath: InverseForeignKey<out Record, VectorStore_384Record>?,
    aliased: Table<VectorStore_384Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VectorStore_384Record>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.vector_store_384</code>
         */
        val VECTOR_STORE_384: VectorStore_384 = VectorStore_384()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VectorStore_384Record> = VectorStore_384Record::class.java

    /**
     * The column <code>public.vector_store_384.id</code>.
     */
    val ID: TableField<VectorStore_384Record, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.vector_store_384.vector_model_id</code>.
     */
    val VECTOR_MODEL_ID: TableField<VectorStore_384Record, Long?> = createField(DSL.name("vector_model_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.vector_store_384.context_info</code>.
     */
    val CONTEXT_INFO: TableField<VectorStore_384Record, JSONB?> = createField(DSL.name("context_info"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.vector_store_384.embedding</code>.
     */
    val EMBEDDING: TableField<VectorStore_384Record, PGvector?> = createField(DSL.name("embedding"), DefaultDataType.getDefaultDataType("\"public\".\"vector\"").nullable(false), this, "", PgVectorBinding())

    private constructor(alias: Name, aliased: Table<VectorStore_384Record>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VectorStore_384Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VectorStore_384Record>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.vector_store_384</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.vector_store_384</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.vector_store_384</code> table reference
     */
    constructor(): this(DSL.name("vector_store_384"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VectorStore_384Record>?, parentPath: InverseForeignKey<out Record, VectorStore_384Record>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, VECTOR_STORE_384, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class VectorStore_384Path : VectorStore_384, Path<VectorStore_384Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VectorStore_384Record>?, parentPath: InverseForeignKey<out Record, VectorStore_384Record>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<VectorStore_384Record>): super(alias, aliased)
        override fun `as`(alias: String): VectorStore_384Path = VectorStore_384Path(DSL.name(alias), this)
        override fun `as`(alias: Name): VectorStore_384Path = VectorStore_384Path(alias, this)
        override fun `as`(alias: Table<*>): VectorStore_384Path = VectorStore_384Path(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_VECTOR_STORE_384_CONTEXT_INFO_GIN)
    override fun getIdentity(): Identity<VectorStore_384Record, Long?> = super.getIdentity() as Identity<VectorStore_384Record, Long?>
    override fun getReferences(): List<ForeignKey<VectorStore_384Record, *>> = listOf(VECTOR_STORE_384__VECTOR_STORE_384_VECTOR_MODEL_ID_FKEY)

    private lateinit var _vectorModels: VectorModelsPath

    /**
     * Get the implicit join path to the <code>public.vector_models</code>
     * table.
     */
    fun vectorModels(): VectorModelsPath {
        if (!this::_vectorModels.isInitialized)
            _vectorModels = VectorModelsPath(this, VECTOR_STORE_384__VECTOR_STORE_384_VECTOR_MODEL_ID_FKEY, null)

        return _vectorModels;
    }

    val vectorModels: VectorModelsPath
        get(): VectorModelsPath = vectorModels()
    override fun `as`(alias: String): VectorStore_384 = VectorStore_384(DSL.name(alias), this)
    override fun `as`(alias: Name): VectorStore_384 = VectorStore_384(alias, this)
    override fun `as`(alias: Table<*>): VectorStore_384 = VectorStore_384(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): VectorStore_384 = VectorStore_384(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): VectorStore_384 = VectorStore_384(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): VectorStore_384 = VectorStore_384(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): VectorStore_384 = VectorStore_384(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): VectorStore_384 = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): VectorStore_384 = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): VectorStore_384 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): VectorStore_384 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): VectorStore_384 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): VectorStore_384 = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): VectorStore_384 = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): VectorStore_384 = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): VectorStore_384 = where(DSL.notExists(select))
}
