/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.semantic_log_classifier_api.db.keys


import com.kbalazsworks.semantic_log_classifier_api.db.tables.FlywaySchemaHistory
import com.kbalazsworks.semantic_log_classifier_api.db.tables.VectorModels
import com.kbalazsworks.semantic_log_classifier_api.db.tables.VectorStore_384
import com.kbalazsworks.semantic_log_classifier_api.db.tables.records.FlywaySchemaHistoryRecord
import com.kbalazsworks.semantic_log_classifier_api.db.tables.records.VectorModelsRecord
import com.kbalazsworks.semantic_log_classifier_api.db.tables.records.VectorStore_384Record

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
val VECTOR_MODELS_PKEY: UniqueKey<VectorModelsRecord> = Internal.createUniqueKey(VectorModels.VECTOR_MODELS, DSL.name("vector_models_pkey"), arrayOf(VectorModels.VECTOR_MODELS.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val VECTOR_STORE_384__VECTOR_STORE_384_VECTOR_MODEL_ID_FKEY: ForeignKey<VectorStore_384Record, VectorModelsRecord> = Internal.createForeignKey(VectorStore_384.VECTOR_STORE_384, DSL.name("vector_store_384_vector_model_id_fkey"), arrayOf(VectorStore_384.VECTOR_STORE_384.VECTOR_MODEL_ID), com.kbalazsworks.semantic_log_classifier_api.db.keys.VECTOR_MODELS_PKEY, arrayOf(VectorModels.VECTOR_MODELS.ID), true)
