/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.semantic_log_classifier_api.db


import com.kbalazsworks.semantic_log_classifier_api.db.tables.FlywaySchemaHistory
import com.kbalazsworks.semantic_log_classifier_api.db.tables.VectorModels
import com.kbalazsworks.semantic_log_classifier_api.db.tables.VectorStore_384

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory get() = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

    /**
     * The table <code>public.vector_models</code>.
     */
    val VECTOR_MODELS: VectorModels get() = VectorModels.VECTOR_MODELS

    /**
     * The table <code>public.vector_store_384</code>.
     */
    val VECTOR_STORE_384: VectorStore_384 get() = VectorStore_384.VECTOR_STORE_384

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
        VectorModels.VECTOR_MODELS,
        VectorStore_384.VECTOR_STORE_384
    )
}
