/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.semantic_log_classifier_api.db.indexes


import com.kbalazsworks.semantic_log_classifier_api.db.tables.FlywaySchemaHistory
import com.kbalazsworks.semantic_log_classifier_api.db.tables.VectorStore_384

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_S_IDX: Index = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS), false)
val IDX_VECTOR_STORE_384_CONTEXT_INFO_GIN: Index = Internal.createIndex(DSL.name("idx_vector_store_384_context_info_gin"), VectorStore_384.VECTOR_STORE_384, arrayOf(VectorStore_384.VECTOR_STORE_384.CONTEXT_INFO), false)
