/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.semantic_log_classifier_api.db.tables.references


import com.kbalazsworks.semantic_log_classifier_api.db.tables.FlywaySchemaHistory
import com.kbalazsworks.semantic_log_classifier_api.db.tables.VectorModels
import com.kbalazsworks.semantic_log_classifier_api.db.tables.VectorStore_384



/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.vector_models</code>.
 */
val VECTOR_MODELS: VectorModels = VectorModels.VECTOR_MODELS

/**
 * The table <code>public.vector_store_384</code>.
 */
val VECTOR_STORE_384: VectorStore_384 = VectorStore_384.VECTOR_STORE_384
