/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.semantic_log_classifier_api.db.tables.records


import com.kbalazsworks.semantic_log_classifier_api.db.tables.VectorStore_384
import com.pgvector.PGvector

import org.jooq.JSONB
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VectorStore_384Record() : TableRecordImpl<VectorStore_384Record>(VectorStore_384.VECTOR_STORE_384) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var vectorModelId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var contextInfo: JSONB?
        set(value): Unit = set(2, value)
        get(): JSONB? = get(2) as JSONB?

    open var embedding: PGvector?
        set(value): Unit = set(3, value)
        get(): PGvector? = get(3) as PGvector?

    /**
     * Create a detached, initialised VectorStore_384Record
     */
    constructor(id: Long? = null, vectorModelId: Long? = null, contextInfo: JSONB? = null, embedding: PGvector? = null): this() {
        this.id = id
        this.vectorModelId = vectorModelId
        this.contextInfo = contextInfo
        this.embedding = embedding
        resetChangedOnNotNull()
    }
}
